### ISSUE TITLE
call stack exceeded

### ISSUE THREAD

**Issue by leviwheatcroft** [arve0/metalsmith-pandoc#11]
call stack exceeded.. maybe due to weird use of multimatch

[here](https://github.com/arve0/metalsmith-pandoc/blob/master/index.js#L44)

```
    async.eachLimit(Object.keys(files), 100, function(file, cb){
      debug('Checking file: %s', file);
      debug('Multimatch: %s %s %s', file, pattern, match(file, pattern))
```

should probably be something like

```
    async.eachLimit(match(Object.keys(files), pattern), 100, function(file, cb){
      debug('Matched: %s %s', file, pattern)
```

**Comment by arve0** [comment]
Thanks for reporting. Can you provide a replicable test scenario that fails?

**Comment by leviwheatcroft** [comment]
Not really sorry.. it came up in [this thread](https://metalsmith.slack.com/archives/C0ANRGT9Q/p1505179255000092).

The plugin call was:
```
.use(
        pandoc({
            from: 'markdown-raw_tex+tex_math_single_backslash',
            to:   'html5',
            pattern: ['**/*.md', '!hljs/**/*', '!Mathjax-master/**/*'],
            ext: '.html',
            args: ['-S', '--highlight-style=tango', '--mathjax']
        })
    )
```

And the stack trace is...
```
[metalsmith-watch] ✓ Live reload server started on port: 35729
/home/dmct/Sitiecillo/node_modules/minimatch/minimatch.js:918
  return s.replace(/\\(.)/g, '$1')
           ^

RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at globUnescape (/home/dmct/Sitiecillo/node_modules/minimatch/minimatch.js:918:12)
    at Minimatch.parse (/home/dmct/Sitiecillo/node_modules/minimatch/minimatch.js:617:12)
    at Array.map (<anonymous>)
    at Minimatch.<anonymous> (/home/dmct/Sitiecillo/node_modules/minimatch/minimatch.js:182:14)
    at Array.map (<anonymous>)
    at Minimatch.make (/home/dmct/Sitiecillo/node_modules/minimatch/minimatch.js:181:13)
    at new Minimatch (/home/dmct/Sitiecillo/node_modules/minimatch/minimatch.js:136:8)
    at Function.minimatch.match (/home/dmct/Sitiecillo/node_modules/minimatch/minimatch.js:689:12)
    at /home/dmct/Sitiecillo/node_modules/multimatch/index.js:25:33
    at Array.reduce (<anonymous>)
    at module.exports (/home/dmct/Sitiecillo/node_modules/multimatch/index.js:17:18)
    at /home/dmct/Sitiecillo/node_modules/metalsmith-pandoc/index.js:44:52
    at /home/dmct/Sitiecillo/node_modules/metalsmith-pandoc/node_modules/async/dist/async.js:3022:16
    at replenish (/home/dmct/Sitiecillo/node_modules/metalsmith-pandoc/node_modules/async/dist/async.js:882:17)
    at iterateeCallback (/home/dmct/Sitiecillo/node_modules/metalsmith-pandoc/node_modules/async/dist/async.js:867:17)
```

**Comment by leviwheatcroft** [comment]
Actually thinking through it a little more, it's not the multimatch call which is causing the stack size to be exceeded, it's calling the callback in the same tick.

See [this issue](https://github.com/caolan/async/issues/75).

Consider [this line](https://github.com/arve0/metalsmith-pandoc/blob/master/index.js#L46). If you have 'x' files in a row which do not pass the multimatch pattern, then your stack will be (at least) 'x' calls deep.

So you could fix it by making line 46 `process.nextTick(cb)`, or just use multimatch to filter files before passing to `async.each` rather than trying to filter them inside the each structure.

**Comment by arve0** [comment]
Sounds like you've found the error. If you submit a PR, I'll work to get it merged.

**Comment by arve0** [comment]
I see that there was a PR already hanging here (sorry @jmatsushita for not merging).

Should be fixed in `v0.2.4`.

**Comment by leviwheatcroft** [comment]
awesome! I didn't see the PR, love your work mate.

**Comment by SrAceves** [comment]
Great job, It works now!

One thing it is suuuper slow: it still cycles through *all* the files --in my case 30680-- in the ignored directory; is that the expected behavior?

**Comment by arve0** [comment]
Yes. Metalsmith reads all files to memory before parsing them. Why do you have so many files?

**Comment by SrAceves** [comment]
I'm using the [mathjax](http://www.mathjax.org) library --with over +30k files!-- which is read from the `.source()` directory. I've tried to ignore the path using `.ignore()` parameter -- as per the metalsmith website -- but it doesn't work. Any ideas?

**Comment by arve0** [comment]
Add mathjax to the build directory instead. For example, put it in a folder
`static` and do a recursive copy `cp -r static/* build`.

**Comment by leviwheatcroft** [comment]
@SrAceves is it possible you've cloned the entire mathjax repo instead of using a package ? That's the only way I could see a browser js lib including that many files. This will cause lots of problems.

There's a bunch of better ways to include client side libs
 * use a CDN (easiest)
 * use webpack (best practice, but bit of a learning curve)
 * just copy [MathJax.js](https://github.com/mathjax/MathJax/blob/master/MathJax.js) into your `src/js` (easy, but means including built code in your repo)

@arve0 's suggestion would solve the immediate problem, but there's other issues like including all that junk in your repo, and having to upload all that junk in your build dir when you want to deploy / host the site.

All that said, this isn't really the best place for this kind of discussion, better to post on the metalsmith slack site.
