### ISSUE TITLE
support for pdf and docx

### ISSUE THREAD

**Issue by arve0** [arve0/metalsmith-pandoc#2]
pandoc doesn't write trough stdout for pdf and docx, which will make convertion to docx and pdf fail

**Comment by eimajenthat** [comment]
I would be willing to commit some time to help fix this, but I'm new to pandoc (and metalsmith, for that matter).  If you've looked into this some already and have some insights to share that might get me further down the road, I'd appreciate it.

**Comment by arve0** [comment]
I have not looked into this, because we have solved our need for PDF with [nodepdf-series](https://github.com/arve0/nodepdf-series) (a fork of nodepdf). [Here](https://github.com/arve0/codeclub_lesson_builder/blob/master/pdf.js) is how we use it with gulp.

Supporting .pdf and .docx should be quite easy though. What you would need to do, is to create a temporary file, use that file as the output for pandoc, then read it into the `files` object of metalsmith.

**Comment by arve0** [comment]
Support for docx fixed in `v1.0.0`, thanks to @saintsal! 

Have not tested PDF, but it should also work.
